using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace _7agz.Core.Service
{
    public static class Services
    {
        public static bool Active = false;
        public static void SendRegisterationEmail(string email, string name)
        {
            #region sending E-mail
            if (Active)
            {
                string subject = $"A7gezly Registration";
                string body = $"Dear {name}, \n" +
                    $"\tThis is a conformation test e-mail generated by A7gezly Project to test an action. It check if the project send an e-mail to the user after registration or not 😁" +
                    $".\nThis feature in debug mode. It does not relased yet.\nPlease ignore this e-mail. \n\n\n" +
                    $"--\nBest regards, \n\nFarrag Abuelela Ahmed\nSoftware Engineer\nMob : +201002289123" +
                    $"\nMob : +201159593928";

                MailAddress from = new MailAddress("a7gazly@gmail.com", "A7gezly");
                MailAddress to = new MailAddress(email);
                MailMessage mc = new MailMessage(from, to);
                mc.Subject = subject;
                mc.Body = body;
                mc.IsBodyHtml = false;
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.Timeout = 1000000;
                smtp.EnableSsl = true;
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                NetworkCredential nc = new NetworkCredential("a7gazly@gmail.com", "vsccadwnfonoxirm");
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = nc;
                smtp.Send(mc);

            }
            #endregion


        }
    }
}
